Settings page
JOOOEG123/cs321-team5-project pull request #18
Opened 2021-10-30 15:40 UTC by rsbbrs

Finished the design for the settings page. It will now change all user information and change the user authentication email if desired. There is only one slight problem, which is that for the email change to go through, it must use a relatively recent login to the account. For now, if the time since last login is too long, it will simply display an error message saying that changes could not be made and that the user should login again. Maybe in the future, we could set up a system for redirecting the user to a login if they try to change their email then preserve account changes. However, I don't think it's a necessary addition right now.

2021-10-30 15:56 UTC, JOOOEG123 approved these changes
You dont have to make the changes. Great Job. I will advice you to check Reactive form and template form in angular. Again, good Job.

2021-10-30 15:56 UTC, JOOOEG123 commented on src/app/pages/settings/settings.component.ts
> +          this.message = 'Please sign-in again to save changes';
Catch error will emit more accurate, error detail.

2021-10-30 15:56 UTC, JOOOEG123 commented on src/app/pages/settings/settings.component.ts
> +      });
is there a reason why you dont unsubscribe. This will cause memory leak.

2021-10-30 15:56 UTC, JOOOEG123 commented on src/app/pages/map-select/map-select.component.html
> +<h1 class="ps-3">My Maps</h1>
dont have to make the changes. You can not use h1 in a sub page.

2021-10-30 16:00 UTC, JOOOEG123 reviewed
Rebase your branch.

2021-10-30 16:05 UTC, JOOOEG123 requested changes
Rebase

2021-10-31 15:56 UTC, JOOOEG123 approved these changes

2021-11-03 15:38 UTC, SGseth-Cmd approved these changes
looks good

2021-11-03 15:40 UTC, merged